use_frameworks!

target 'WVideoRecoder_Example' do
  pod 'WVideoRecoder', :path => '../'

  target 'WVideoRecoder_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
