source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zzttwzq/WSpecRepo.git'

use_frameworks!

target 'WVideoRecoder_Example' do
  pod 'WVideoRecoder', :path => '../'
  pod 'WVideoPlayer'
end
